'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class formulario_IBIS

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ASPxTextBoxNombreApellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxNombreApellido As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxEmail As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxTelefono As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxRadioButtonListActividadDedica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonListActividadDedica As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxDateEditFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxDateEditFecha As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxTimeEditHora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTimeEditHora As Global.DevExpress.Web.ASPxTimeEdit

    '''<summary>
    '''ASPxComboBoxAeropuertos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxAeropuertos As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceAeropuertos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAeropuertos As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxTextBoxPista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxPista As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxCoordenadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxCoordenadas As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxRadioButtonCoordenadasNorteSur control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonCoordenadasNorteSur As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxTextBoxAlturaPies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxAlturaPies As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxVelocidadIndicada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxVelocidadIndicada As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxComboBoxCondicionesLuz control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxCondicionesLuz As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxTextBoxIdentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxIdentificacion As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxOperador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxOperador As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxTipoAeronave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxTipoAeronave As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxModeloMotor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxModeloMotor As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxPosicionRuta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxPosicionRuta As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxRadioButtonListFaseVuelo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonListFaseVuelo As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxRadioButtonListCantidadAvesObservadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonListCantidadAvesObservadas As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxCheckBoxListPartesGolpeadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCheckBoxListPartesGolpeadas As Global.DevExpress.Web.ASPxCheckBoxList

    '''<summary>
    '''ASPxCheckBoxListConsecuenciasVuelo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCheckBoxListConsecuenciasVuelo As Global.DevExpress.Web.ASPxCheckBoxList

    '''<summary>
    '''ASPxCheckBoxListCondicionesCielo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCheckBoxListCondicionesCielo As Global.DevExpress.Web.ASPxCheckBoxList

    '''<summary>
    '''ASPxRadioButtonListCantidadAvesGolpeadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonListCantidadAvesGolpeadas As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxTextBoxIdentificacionfauna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxIdentificacionfauna As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxCheckBoxListPartesDaniadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCheckBoxListPartesDaniadas As Global.DevExpress.Web.ASPxCheckBoxList

    '''<summary>
    '''ASPxCheckBoxListPrecipitacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCheckBoxListPrecipitacion As Global.DevExpress.Web.ASPxCheckBoxList

    '''<summary>
    '''ASPxRadioButtonListTamanioAves control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonListTamanioAves As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxRadioButtonListAdvertenciaPiloto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonListAdvertenciaPiloto As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxTextBoxTiempoFueraServicioAeronave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxTiempoFueraServicioAeronave As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxCostoReparacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxCostoReparacion As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxMemoDescripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxMemoDescripcion As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''ASPxTextBoxOtrosCostos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxOtrosCostos As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxUploadControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxUploadControl1 As Global.DevExpress.Web.ASPxUploadControl

    '''<summary>
    '''ASPxButtonEnviar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButtonEnviar As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''HiddenFieldValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldValor As Global.DevExpress.Web.ASPxHiddenField

    '''<summary>
    '''ASPxPopupControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl2 As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxButtonRegresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButtonRegresar As Global.DevExpress.Web.ASPxButton
End Class
