'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Dashboard2
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("sspbi.Dashboard2", GetType(Dashboard2).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PERhdGFTZXQgTmFtZT0iU1FMIERhdGEgU291cmNlIDEiPjxWaWV3IE5hbWU9IlJlcG9ydGVzX1NTUF9NYXN0ZXIiPjxGaWVsZCBOYW1lPSJpZCIgVHlwZT0iSW50NjQiIC8+PEZpZWxkIE5hbWU9ImNpdWRhZCIgVHlwZT0iU3RyaW5nIiAvPjxGaWVsZCBOYW1lPSJwYWlzIiBUeXBlPSJTdHJpbmciIC8+PEZpZWxkIE5hbWU9ImFlcm9wdWVydG8iIFR5cGU9IlN0cmluZyIgLz48RmllbGQgTmFtZT0iYWVyb2Ryb21vIiBUeXBlPSJTdHJpbmciIC8+PEZpZWxkIE5hbWU9InB1bnRvX3J1dGFfb2FjaSIgVHlwZT0iU3RyaW5nIiAvPjxGaWVsZCBOYW1lPSJwdW50b19ydXRhX2lhdGEiIFR5cGU9IlN0cmluZyIgLz48RmllbGQgTmFtZT0iYWVyb3BfZGVzY3JpcCIgVHlwZT0iU3RyaW5n [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property DashboardSqlDataSource1_ResultSchemaSerializable() As String
            Get
                Return ResourceManager.GetString("DashboardSqlDataSource1.ResultSchemaSerializable", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
