'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class formulario_ATS

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ASPxTextBoxNombreApellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxNombreApellido As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxEmail As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxTelefono As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxRadioButtonPosicionSuceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonPosicionSuceso As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxTextBoxPosicionActividadDuranteSuceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxPosicionActividadDuranteSuceso As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxDateEditFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxDateEditFecha As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxTimeEditHora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTimeEditHora As Global.DevExpress.Web.ASPxTimeEdit

    '''<summary>
    '''ASPxComboBoxAeropuertos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxAeropuertos As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceAeropuertos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceAeropuertos As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxComboBoxRadioAyuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxRadioAyuda As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceRadioayuda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRadioayuda As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxComboBoxWaypoint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxWaypoint As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceWaypoint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceWaypoint As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxComboBoxRutaAerovia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxRutaAerovia As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceRutaAerovia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceRutaAerovia As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxTextBoxHorizontalNM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxHorizontalNM As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxVerticalFT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxVerticalFT As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxComboBoxCondicionesMET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxCondicionesMET As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceCondicionesMET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceCondicionesMET As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxTextBoxVisibilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxVisibilidad As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxComboBoxFenomenoMET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxFenomenoMET As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceFenomenoMET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceFenomenoMET As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxTextBoxRVR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxRVR As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxComboBoxDependenciaATS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxDependenciaATS As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceDependenciaATS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceDependenciaATS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxComboBoxEspacioAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxEspacioAereo As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''SqlDataSourceEspacioAereo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSourceEspacioAereo As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxRadioButtonTipoIncidente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonTipoIncidente As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxTextBoxOtroIncidente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxOtroIncidente As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxVuelo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxVuelo1 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxOperadorO1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxOperadorO1 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxTipoAeronave1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxTipoAeronave1 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxRadioButtonFaseVuelo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonFaseVuelo1 As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxTextBoxFaseVueloOtro1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxFaseVueloOtro1 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxComboBoxAeropuertos1Salida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxAeropuertos1Salida As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxComboBoxAeropuertos1Destino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxAeropuertos1Destino As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxTextBoxModeloNV1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxModeloNV1 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxVuelo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxVuelo2 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxOperadorO2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxOperadorO2 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxTextBoxTipoAeronave2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxTipoAeronave2 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxRadioButtonFaseVuelo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxRadioButtonFaseVuelo2 As Global.DevExpress.Web.ASPxRadioButtonList

    '''<summary>
    '''ASPxTextBoxFaseVueloOtro2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxFaseVueloOtro2 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxComboBoxAeropuertos2Salida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxAeropuertos2Salida As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxComboBoxAeropuertos2Destino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBoxAeropuertos2Destino As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxTextBoxNumeroVueloNV2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBoxNumeroVueloNV2 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxMemoDescripcionNarrativa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxMemoDescripcionNarrativa As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''ASPxUploadControlArchivos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxUploadControlArchivos As Global.DevExpress.Web.ASPxUploadControl

    '''<summary>
    '''ASPxButtonEnviar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButtonEnviar As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''HiddenFieldValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenFieldValor As Global.DevExpress.Web.ASPxHiddenField

    '''<summary>
    '''ASPxPopupControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl2 As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton2 As Global.DevExpress.Web.ASPxButton
End Class
